# Generated by Django 3.2.18 on 2023-05-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duoc_djangobackend', '0002_alter_cuentapresupuestaria_id_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='id_anexo',
            field=models.IntegerField(unique=True),
        ),
    ]
