# Generated by Django 4.1.8 on 2023-05-16 14:32
# Generated by Django 4.1.8 on 2023-05-10 00:45

from django.db import migrations
from ..anexo_operations import calculo_mensual_general



def calculo_data(apps, schema_editor):
    try:
        calculo_mensual_general(5,1)
    except Exception as e:
        print(f'Error al calcular el mensual de la facultad: {e}')
        exit(1)
class Migration(migrations.Migration):

    dependencies = [
        ('duoc_djangobackend', '0003_add_insert_calculo_unidad'),
    ]

    operations = [
        migrations.RunPython(calculo_data),
    ]